### ISSUE TITLE
CalendarPicker / TimePicker how to change icon (on the right othe text field)

### ISSUE THREAD

**Issue by ouaibsky** [dlsc-software-consulting-gmbh/GemsFX#108]
Hello

I would like to replace icon of those picker and use something like ikonly.
Is there an easy way to do this ?
I know we can configure with -fx-shape but it's pure SVG.

I notices that ikonly is already defines as a dependency.
If not, does it make sens to propose a PR in that way ?

**Comment by dlemmermann** [comment]
No, it does not. We intentionally used SVG because it makes it possible to replace the icons via pure CSS. I am a big fan of Ikonli but for libs like GemsFX it makes a lot of sense to use SVG. We have a page on jfxcentral that gives you the SVG path for 50,000+ Ikonli icons. I am pretty sure you will find one there.

https://www.jfx-central.com/icons

<img width="1346" alt="Bildschirmfoto 2024-01-13 um 14 13 02" src="https://github.com/dlsc-software-consulting-gmbh/GemsFX/assets/9534301/148a7d1f-39ec-4b7c-9fe2-7ff4b2dd5989">

**Comment by ouaibsky** [comment]
Ok it makes sens
Thanks you for hints.
Chris.
